import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_compoenents/Navbar";
import Providers from "./_compoenents/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Daily Digest - Update World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${inter.className} bg-gray-100 dark:bg-zinc-900 transition-all duration-700`}
      >
        <Providers attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange >
          <div className="max-w-6xl mx-auto">
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
